---
version: '3'
services:
  app:
    build:
      context: ./backend/peking_web/.
    environment:
      PGHOST: db
    volumes:
      - ./backend/peking_web/:/app
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: peking
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db.sql:/db.sql
  media:
    build: ./backend/peking_media
    ports:
      - "1935:1935"
      - "9090:9090"
      - "9443:9443"
    volumes:
      - ./ssl:/etc/ssl/
    environment:
      MEDIA_SERVER: app:4000
  nginx:
    image: nginx:latest
    restart: always
    container_name: production_peking_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
volumes:
  pgdata:
